module:
  description: postgres container
  type: container
  name: postgres
  image: postgres:9.4
  services:
    - name: postgres-service
      volumes:
        - name: data
          containerPath: /db-data
      ports:
        - name: db
          containerPort: 5432
