name: Node CI

on:
  release:
    types: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Setup git
      run: |
        eval "$(ssh-agent -s)"
        mkdir -p ~/.ssh
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        ssh-add <(echo "${{ secrets.DEPLOY_KEY_HOMEBREW_GARDEN }}")
        sudo chmod 600 ~/.ssh/id_rsa
        sudo chmod 600 ~/.ssh/id_rsa.pub
        sudo git config user.email "admin@garden.io"
        sudo git config user.name "Github Action"
    - name: npm install
      run: |
        npm install
        npm install -g gulp
        gulp update-brew
