name: Node CI

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install
      run: |
        npm install
        npm install -g gulp
        gulp update-brew
